replicaCount: 1
containerPort: 8000

image:
  repository: docker.dev.hybrit.io/hybrit-demo-saleor-core
  pullPolicy: Always

imagePullSecrets:
  - name: docker-cfg

service:
  type: ClusterIP
  port: 80

probes:
  enabled: true
  probePath: /graphql
  livenessProbe:
    initialDelaySeconds: 25
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 600
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 40
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 600
    failureThreshold: 5
  terminationGracePeriodSeconds: 10

env:
  - name: ALLOWED_CLIENT_HOSTS
    value: "*"
  - name: ALLOWED_HOSTS
    value: "*"
  - name: DATABASE_URL
    value: "postgres://viscon_admin@viscon-postgres-weu:dB9KGA0KesoR@viscon-postgres-weu.postgres.database.azure.com:5432/saleor-test-db"
  - name: DEFAULT_FROM_EMAIL
    value: "no-reply@hybrit.org"
  - name: SECRET_KEY
    value: "945672686761362652"
  - name: DEFAULT_CURRENCY
    value: "EUR"
  - name: EMAIL_URL
    value: "smtp://apikey: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@smtp.sendgrid.com:465/?ssl=True"
  - name: DEFAULT_COUNTRY
    value: "NL"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/client-max-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "ecommerce-portal.core.demo.hybrit.io"
      path: /
  tls:
    - hosts:
        - "ecommerce-portal.core.demo.hybrit.io"
      secretName: "ecommerce-portal-ingress-cert"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
